export const ICONS = {
  arrowDown: '/icons/arrow-down.svg',
  arrowUp: '/icons/arrow-up.svg',
  arrowLeft: '/icons/arrow-left.svg',
  arrowRight: '/icons/arrow-right.svg',
  meatball: '/icons/meatball.svg',
  meatballGray: '/icons/meatball-gray.svg',
  toastError: '/icons/toast-error.svg',
  toastSuccess: '/icons/toast-success.svg',
  addListCheck: '/icons/add-list-check.svg',
  addListRadio: '/icons/add-list-radio.svg',
  addListText: '/icons/add-list-text.svg',
  close: '/icons/close.svg',
  calendar: '/icons/calender.svg',
  kakao: '/icons/kakao.svg',
  drag: '/icons/drag.svg',
  infoCircle: '/icons/info-circle.svg',
  checkCircle: '/icons/check-circle.svg',
  plus: '/icons/plus.svg',
  search: '/icons/search.svg',
};
